server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-doctors
              uri: lb://user-service
              predicates:
                - Path=/api/doctors,/api/doctors/**
            - id: user-service-patients
              uri: lb://user-service
              predicates:
                - Path=/api/patients,/api/patients/**

            - id: clinical-service-examinations
              uri: lb://clinical-service
              predicates:
                - Path=/api/examinations,/api/examinations/**
            - id: clinical-service-sick-leaves
              uri: lb://clinical-service
              predicates:
                - Path=/api/sick-leaves,/api/sick-leaves/**
            - id: clinical-service-diagnoses
              uri: lb://clinical-service
              predicates:
                - Path=/api/diagnoses,/api/diagnoses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true