server:
  port: 8081 # ???? ?????? ?? ?????? ?? ???? 8081

spring:
  application:
    name: user-service

  # 1. ?????? ? PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  # 2. ????????? ?? Hibernate (??????????? ????????? ?? ???????)
  jpa:
    hibernate:
      ddl-auto: update # ??????????? ???????? ?????????, ?????? ???????? Java ?????????
    show-sql: true # ??????? SQL ???????? ? ????????? (??????? ?? ?????????)
    properties:
      hibernate:
        format_sql: true

  # 3. ?????? ? Keycloak (?????????)
  security:
    oauth2:
      resourceserver:
        jwt:
          # ?????: ??? "medical-realm" ?????? ?? ? ????? ?????, ????? ???? ? Keycloak
          issuer-uri: http://localhost:8080/realms/medical-realm